services:
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: '{DB_NAME}'
      POSTGRES_USER: '{DB_USER}'
      POSTGRES_PASSWORD: '{DB_PASSWORD}'
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: my-weak-password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db
